#+TITLE: Iddo's Vanilla Emacs Config
#+PROPERTY: header-args :tangle init.el
#+auto_tangle: t
#+OPTIONS: toc

* Table of Contents :toc:
- [[#setting-up-package-and-use-package][Setting up =package= and =use-package=]]
- [[#general-settings][General settings]]
  - [[#personal-info][Personal Info]]
  - [[#lines-numbers][Lines numbers]]
  - [[#theme][Theme]]
  - [[#recent-files][Recent Files]]
  - [[#remove-all-bars][Remove All Bars]]
  - [[#path-workaround-in-osx][PATH workaround in OSX]]
  - [[#org-mode][Org Mode]]
- [[#core-packages][Core Packages]]
  - [[#evil-mode][Evil Mode]]
  - [[#ivy][Ivy]]
  - [[#avy][Avy]]
  - [[#yasnippet][Yasnippet]]
  - [[#magit][Magit]]
- [[#latex-editing][LaTeX Editing]]
  - [[#bind-tex-files-to-latex-mode][Bind .tex files to LaTeX-mode]]
  - [[#hook-evil-tex-mode][Hook evil-tex-mode]]
  - [[#pdftools][PDFTools]]
  - [[#auctex-cdlatex-and-preview][AucTeX, CDLateX and preview]]
  - [[#display-hebrew-upside-down][Display Hebrew Upside Down]]
  - [[#prettify-symbols][Prettify Symbols]]
  - [[#cdlatex-integration-with-yasnippet][CDLaTeX integration with YaSnippet]]
  - [[#lazytab--array-and-matrix-support][Lazytab / Array and Matrix support]]
  - [[#pdf][PDF]]
  - [[#hooks][Hooks]]
- [[#doom-keybindings][Doom Keybindings]]
  - [[#leader-key][Leader Key]]
  - [[#basic-motions][Basic Motions]]
  - [[#file-keybindings-spc-f][File Keybindings (SPC-f)]]
  - [[#buffer-keybindings-spc-b][Buffer Keybindings (SPC-b)]]
  - [[#window-keybindings-spc-w][Window Keybindings (SPC-w)]]
  - [[#open-keybindings-spc-o][Open Keybindings (SPC-o)]]
  - [[#magit-keybindings-spc-g][Magit Keybindings (SPC-g)]]
  - [[#dired-keybindings][Dired Keybindings]]
- [[#org-mode-packages][Org Mode Packages]]
  - [[#org-auto-tangle][org-auto-tangle]]
  - [[#toc-org-mode][toc-org-mode]]

* Setting up =package= and =use-package=
#+BEGIN_SRC emacs-lisp
(require 'package) ;; Emacs builtin

;; set package.el repositories
(setq package-archives
'(
   ("org" . "https://orgmode.org/elpa/")
   ("gnu" . "https://elpa.gnu.org/packages/")
   ("melpa" . "https://melpa.org/packages/")
))

;; initialize built-in package management
(package-initialize)

;; update packages list if we are on a new install
(unless package-archive-contents
  (package-refresh-contents))

;; a list of pkgs to programmatically install
;; ensure installed via package.el
(setq my-package-list '(use-package))

;; programmatically install/ensure installed
;; pkgs in your personal list
(dolist (package my-package-list)
  (unless (package-installed-p package)
    (package-install package)))
#+END_SRC

;; ----------------------------------------------


* General settings
** Personal Info
#+BEGIN_SRC emacs-lisp
;; Basic
(setq user-full-name "Ido Merenstein"
      user-mail-address "m.ido@campus.technion.ac.il")
#+END_SRC

** Lines numbers
#+BEGIN_SRC emacs-lisp
(global-display-line-numbers-mode)
(setq display-line-numbers-type 'relative)
#+END_SRC emacs-lisp
** Theme
Define a theme.
#+BEGIN_SRC emacs-lisp
(use-package doom-themes
  :ensure t
  :config
  ;; Global settings (defaults)
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
        doom-themes-enable-italic t) ; if nil, italics is universally disabled
  (load-theme 'doom-outrun-electric t))
#+END_SRC

Change ivy face.
#+begin_src emacs-lisp
(custom-set-faces
 '(ivy-current-match
   ((((class color) (background light))
     :background "red" :foreground "white")
    (((class color) (background dark))
     :background "#6F1AB6" :foreground "#FFA3FD"))))
#+end_src
** Recent Files
#+BEGIN_SRC emacs-lisp
(recentf-mode 1)
(setq recentf-max-menu-items 25)
(setq recentf-max-saved-items 25)
#+END_SRC

** Remove All Bars
#+BEGIN_SRC emacs-lisp
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
#+END_SRC
** PATH workaround in OSX
https://stackoverflow.com/questions/3517165/pdflatex-command-not-working-in-emacs-terminal-mode
On OS X, environment variables for GUI programs are set in ~/.MacOSX/environment.plist. There are many Emacs specific work arounds like using
=(setenv "PATH" (shell-command-to-string "echo -n $PATH"))= which you can find scattered across Stack Overflow and the internet in general.

#+begin_src emacs-lisp
(setenv "PATH" (shell-command-to-string "echo -n $PATH"))
#+end_src

** Org Mode
*** Basic Org Settings
#+begin_src emacs-lisp
;; (add-hook 'org-mode-hook #'org-fragtog-mode)
#+end_src

Set the org directory.
#+begin_src emacs-lisp
(setq org-directory "~/org/")
#+end_src

Turn on CDLaTeX minor mode.

#+begin_src emacs-lisp
(add-hook
'org-mode-hook #'turn-on-org-cdlatex)
#+end_src

Allow auto LaTeX previewing.
*I have currently disabled this because it messes with LaTeX LazyTab*
#+begin_src emacs-lisp
;; (add-hook 'org-mode-hook #'org-fragtog-mode)
#+end_src
*** Appearance

Replace the default asteriks for bullets.
#+begin_src emacs-lisp
  (use-package org-bullets
    :ensure t
    :config
    (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+end_src

Make titles bigger.

#+begin_src emacs-lisp
(custom-set-faces
  '(org-level-1 ((t (:inherit outline-1 :height 1.5))))
  '(org-level-2 ((t (:inherit outline-2 :height 1.4))))
  '(org-level-3 ((t (:inherit outline-3 :height 1.3))))
  '(org-level-4 ((t (:inherit outline-4 :height 1.2))))
  '(org-level-5 ((t (:inherit outline-5 :height 1.1))))
)
#+end_src


* Core Packages
** Evil Mode
#+BEGIN_SRC emacs-lisp
  ;; https://systemcrafters.cc/emacs-from-scratch/key-bindings-and-evil/
  (defun rune/evil-hook ()
    (dolist (mode '(custom-mode
		    eshell-mode
		    git-rebase-mode
		    erc-mode
		    circe-server-mode
		    circe-chat-mode
		    circe-query-mode
		    sauron-mode
		    term-mode))
      (add-to-list 'evil-emacs-state-modes mode)))


  (use-package evil
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump nil)
    (setq evil-overriding-maps nil)
    (require 'evil)
    :hook (evil-mode . rune/evil-hook)
    :config
    (evil-mode 1)
    (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
    (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)
    (evil-set-undo-system 'undo-redo)

    ;; Use visual line motions even outside of visual-line-mode buffers
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal))

    (use-package evil-collection
    :after evil
    :ensure t
    :custom
    (evil-collection-setup-minibuffer t)
    :config
    (evil-collection-init))
#+END_SRC

** Ivy
#+BEGIN_SRC emacs-lisp
(use-package counsel
  :after ivy
  :config (counsel-mode))

(use-package ivy
  :defer 0.1
  :diminish
  :bind (("C-c C-r" . ivy-resume)
         ("C-x B" . ivy-switch-buffer-other-window))
  :custom
  (ivy-count-format "(%d/%d) ")
  (ivy-use-virtual-buffers t)
  :config (ivy-mode))

;;(use-package ivy-rich
  ;;:after ivy
  ;;:custom
  ;;(ivy-virtual-abbreviate 'full
                          ;;ivy-rich-switch-buffer-align-virtual-buffer t
                          ;;ivy-rich-path-style 'abbrev)
  ;;:config
  ;;(ivy-set-display-transformer 'ivy-switch-buffer
                               ;;'ivy-rich-switch-buffer-transformer))

(use-package swiper
  :after ivy
  :bind (("C-s" . swiper)
         ("C-r" . swiper)))
#+END_SRC

Change Ivy frame height
#+BEGIN_SRC emacs-lisp
(setq ivy-height-alist
      '((t
         lambda (_caller)
         (/ (frame-height) 1.5))))
#+END_SRC

** Avy
#+BEGIN_SRC emacs-lisp
(use-package avy
  :ensure t
  :config
  (require 'avy))
#+END_SRC

** Yasnippet
Set YaSnippet directory.

#+begin_src emacs-lisp
(setq yas-snippet-dirs '("~/.emacs.d/snippets"))
#+end_src

General 'use-package' settings.

#+begin_src emacs-lisp
  (use-package yasnippet
    :ensure t
    :hook ((LaTeX-mode . yas-minor-mode)
	   (post-self-insert . my/yas-try-expanding-auto-snippets))
    :config
    (require 'yasnippet)
    (yas-global-mode 1)
    (use-package warnings
      :config
      (cl-pushnew '(yasnippet backquote-change)
		  warning-suppress-types
		  :test 'equal))

    (setq yas-triggers-in-field t)

    ;; Function that tries to autoexpand YaSnippets
    ;; The double quoting is NOT a typo!
    (defun my/yas-try-expanding-auto-snippets ()
      (when (and (boundp 'yas-minor-mode) yas-minor-mode)
	(let ((yas-buffer-local-condition ''(require-snippet-condition . auto)))
	  (yas-expand)))))
#+end_src

*** Auto expanding YaSnippets

This snippet of code sets up YaSnippet autoexpanding.
#+begin_src emacs-lisp
;; Try after every insertion
(add-hook 'post-self-insert-hook #'my/yas-try-expanding-auto-snippets)
#+end_src


Not 100% sure what this does (revisit said blog post):
#+begin_src emacs-lisp
;; YaSnippet complains if we use a snippet to edit the buffer directly,
;; as we do with the above examples of wrapping symbols in \hat{}, etc. This is probably bad practice, but I haven’t had an issue yet. I suppress these warnings with

(with-eval-after-load 'warnings
  (cl-pushnew '(yasnippet backquote-change) warning-suppress-types
              :test 'equal))
#+end_src



** Magit
#+begin_src emacs-lisp
  (use-package magit
    :ensure t)
#+end_src

* LaTeX Editing
Most of these settings have been directly yanked from [[https://karthinks.com/software/latex-input-for-impatient-scholars/][this blog post]] by karthinks.
I have added several other lines to cater to my needs.
This part of my config needs to be explored more.

** Bind .tex files to LaTeX-mode
#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.tex\\'" . LaTeX-mode))
#+end_src

I am using the XeTeX engine to compile because of its Hebrew support.
#+begin_src emacs-lisp
;; Set default TeX engine to XeTeX
(setq-default TeX-engine 'xetex)

(setq TeX-PDF-mode t)
#+end_src

** Hook evil-tex-mode
#+begin_src emacs-lisp
(add-hook 'LaTeX-mode-hook #'evil-tex-mode)
#+end_src

** PDFTools
#+begin_src emacs-lisp
  (use-package pdf-tools
    :ensure t
    :config
    (pdf-tools-install)
    (with-eval-after-load 'pdf-view 
        (define-key pdf-view-mode-map (kbd "SPC") nil)))

    (setq TeX-view-program-selection '((output-pdf "PDF Tools")))
#+end_src


** AucTeX, CDLateX and preview
#+begin_src emacs-lisp
    ;; AucTeX settings - almost no changes
    (use-package latex
      :ensure auctex
      :hook ((LaTeX-mode . prettify-symbols-mode))
      :bind (:map LaTeX-mode-map
	     ("C-S-e" . latex-math-from-calc))
      :config
      ;; Format math as a Latex string with Calc
      (defun latex-math-from-calc ()
	"Evaluate `calc' on the contents of line at point."
	(interactive)
	(cond ((region-active-p)
	       (let* ((beg (region-beginning))
		      (end (region-end))
		      (string (buffer-substring-no-properties beg end)))
		 (kill-region beg end)
		 (insert (calc-eval `(,string calc-language latex
					      calc-prefer-frac t
					      calc-angle-mode rad)))))
	      (t (let ((l (thing-at-point 'line)))
		   (end-of-line 1) (kill-line 0)
		   (insert (calc-eval `(,l
					calc-language latex
					calc-prefer-frac t
					calc-angle-mode rad))))))))

    (use-package preview
      :after latex
      :hook ((LaTeX-mode . preview-larger-previews))
      :config
      (defun preview-larger-previews ()
	(setq preview-scale-function
	      (lambda () (* 1.25
		       (funcall (preview-scale-from-face)))))))

    ;; CDLatex settings
  (use-package cdlatex
    :ensure t
    :hook (LaTeX-mode . turn-on-cdlatex)
    :bind (:map cdlatex-mode-map 
		("<tab>" . cdlatex-tab)))
#+end_src

** Display Hebrew Upside Down
RTL reordering is a pain while taking notes, therefore I have decided to alter
the 'bidi-display-reordering variable to make everything completely LTR
while editing TeX files.

#+begin_src emacs-lisp
(defun flip-hebrew ()
  (setq bidi-display-reordering nil))
#+end_src

** Prettify Symbols
For added readability, I have added the following symbols:
#+begin_src emacs-lisp
(defun prettify-latex-symbols ()
  (interactive)
   "Prettify LaTex parenthesis"
   (push '("\\left[ " .  "【") prettify-symbols-alist)
   (push '(" \\right]" . "】" ) prettify-symbols-alist)
   (push '("\\left( " .  "(") prettify-symbols-alist)
   (push '(" \\right)" . ")" ) prettify-symbols-alist)
   (push '("\\left| " .  "|") prettify-symbols-alist)
   (push '(" \\right|" . "|" ) prettify-symbols-alist)

   (push '("\\left[".  "[") prettify-symbols-alist)
   (push '("\\right]" ."]" ) prettify-symbols-alist)
   (push '("\\left(".  "(") prettify-symbols-alist)
   (push '("\\right)" .")" ) prettify-symbols-alist)
   (push '("\\left|".  "|") prettify-symbols-alist)
   (push '("\\right|" ."|" ) prettify-symbols-alist)

   (push '(" \\left\( ".  "(") prettify-symbols-alist)

   (push '("\\left{ " .  "⎨") prettify-symbols-alist)
   (push '(" \\right}" . "⎬" ) prettify-symbols-alist)

   (push '("\\left{".  "⎨") prettify-symbols-alist)
   (push '("\\right}" ."⎬" ) prettify-symbols-alist)

   (push '("\\left\\{".  "⎨") prettify-symbols-alist)
   (push '("\\right\\}" ."⎬" ) prettify-symbols-alist)

   (push '("\\left< ".  "<") prettify-symbols-alist)
   (push '(" \\right>" .">" ) prettify-symbols-alist)

   (push '("\\frac{" ."{" ) prettify-symbols-alist)
   (push '("$" ."ﾟ" ) prettify-symbols-alist)
   (push '("\\Delta " ."Δ" ) prettify-symbols-alist)
   (push '("\\mathrm{d}" ."d") prettify-symbols-alist)

   (push '("\\coloneqq" ."≔") prettify-symbols-alist)

   (push '("\\mathbb{C}" ."ℂ") prettify-symbols-alist)

   (push '("\\divides" ."|") prettify-symbols-alist)

   (push '("\\sqrt" ."√") prettify-symbols-alist)

   (prettify-symbols-mode))
#+end_src

** CDLaTeX integration with YaSnippet
This supposedly takes care of CDLaTeX integration with YaSnippet:

#+begin_src emacs-lisp
;; CDLatex integration with YaSnippet: Allow cdlatex tab to work inside Yas
;; fields
(use-package cdlatex
  :hook ((cdlatex-tab . yas-expand)
         (cdlatex-tab . cdlatex-in-yas-field)))

  (use-package yasnippet
    :bind (:map yas-keymap
           ("<tab>" . yas-next-field-or-cdlatex)
           ("TAB" . yas-next-field-or-cdlatex))
    :config
    (defun cdlatex-in-yas-field ()
      ;; Check if we're at the end of the Yas field
      (when-let* ((_ (overlayp yas--active-field-overlay))
                  (end (overlay-end yas--active-field-overlay)))
        (if (>= (point) end)
            ;; Call yas-next-field if cdlatex can't expand here
            (let ((s (thing-at-point 'sexp)))
              (unless (and s (assoc (substring-no-properties s)
                                    cdlatex-command-alist-comb))
                (yas-next-field-or-maybe-expand)
                t))
          ;; otherwise expand and jump to the correct location
          (let (cdlatex-tab-hook minp)
            (setq minp
                  (min (save-excursion (cdlatex-tab)
                                       (point))
                       (overlay-end yas--active-field-overlay)))
            (goto-char minp) t)))))

    (defun yas-next-field-or-cdlatex nil
      (interactive)
      "Jump to the next Yas field correctly with cdlatex active."
      (if
          (or (bound-and-true-p cdlatex-mode)
              (bound-and-true-p org-cdlatex-mode))
          (cdlatex-tab)
        (yas-next-field-or-maybe-expand)))
#+end_src

** Lazytab / Array and Matrix support
This snippet makes editing arrays and matrices easier using Lazytab and org-table.

#+begin_src emacs-lisp
;; Array/tabular input with org-tables and cdlatex
(use-package org-table
  :after cdlatex
  :bind (:map orgtbl-mode-map
              ("<tab>" . lazytab-org-table-next-field-maybe)
              ("TAB" . lazytab-org-table-next-field-maybe))
  :init
  (add-hook 'cdlatex-tab-hook 'lazytab-cdlatex-or-orgtbl-next-field 90)
  ;; Tabular environments using cdlatex
  (add-to-list 'cdlatex-command-alist '("smat" "Insert smallmatrix env"
                                       "\\left( \\begin{smallmatrix} ? \\end{smallmatrix} \\right)"
                                       lazytab-position-cursor-and-edit
                                       nil nil t))
  (add-to-list 'cdlatex-command-alist '("bmat" "Insert bmatrix env"
                                       "\\begin{bmatrix} ? \\end{bmatrix}"
                                       lazytab-position-cursor-and-edit
                                       nil nil t))
  (add-to-list 'cdlatex-command-alist '("pmat" "Insert pmatrix env"
                                       "\\begin{pmatrix} ? \\end{pmatrix}"
                                       lazytab-position-cursor-and-edit
                                       nil nil t))
  (add-to-list 'cdlatex-command-alist '("tbl" "Insert table"
                                        "\\begin{table}\n\\centering ? \\caption{}\n\\end{table}\n"
                                       lazytab-position-cursor-and-edit
                                       nil t nil))
  :config
  ;; Tab handling in org tables
  (defun lazytab-position-cursor-and-edit ()
    ;; (if (search-backward "\?" (- (point) 100) t)
    ;;     (delete-char 1))
    (cdlatex-position-cursor)
    (lazytab-orgtbl-edit))

  (defun lazytab-orgtbl-edit ()
    (advice-add 'orgtbl-ctrl-c-ctrl-c :after #'lazytab-orgtbl-replace)
    (orgtbl-mode 1)
    (open-line 1)
    (insert "\n|"))

  (defun lazytab-orgtbl-replace (_)
    (interactive "P")
    (unless (org-at-table-p) (user-error "Not at a table"))
    (let* ((table (org-table-to-lisp))
           params
           (replacement-table
            (if (texmathp)
                (lazytab-orgtbl-to-amsmath table params)
              (orgtbl-to-latex table params))))
      (kill-region (org-table-begin) (org-table-end))
      (open-line 1)
      (push-mark)
      (insert replacement-table)
      (align-regexp (region-beginning) (region-end) "\\([:space:]*\\)& ")
      (orgtbl-mode -1)
      (advice-remove 'orgtbl-ctrl-c-ctrl-c #'lazytab-orgtbl-replace)))

  (defun lazytab-orgtbl-to-amsmath (table params)
    (orgtbl-to-generic
     table
     (org-combine-plists
      '(:splice t
                :lstart ""
                :lend " \\\\"
                :sep " & "
                :hline nil
                :llend "")
      params)))

  (defun lazytab-cdlatex-or-orgtbl-next-field ()
    (when (and (bound-and-true-p orgtbl-mode)
               (org-table-p)
               (looking-at "[[:space:]]*\\(?:|\\|$\\)")
               (let ((s (thing-at-point 'sexp)))
                 (not (and s (assoc s cdlatex-command-alist-comb)))))
      (call-interactively #'org-table-next-field)
      t))

  (defun lazytab-org-table-next-field-maybe ()
    (interactive)
    (if (bound-and-true-p cdlatex-mode)
        (cdlatex-tab)
      (org-table-next-field))))
#+end_src

** PDF
Open PDF files using pdf-tools.
#+begin_src emacs-lisp
(setq TeX-view-program-selection '((output-pdf "PDF Tools"))
      TeX-source-correlate-start-server t)
#+end_src

Update PDF buffers after a TeX file successfully compiles.
#+begin_src emacs-lisp
;; Update PDF buffers after successful LaTeX runs
(add-hook 'TeX-after-compilation-finished-functions
           #'TeX-revert-document-buffer)
#+end_src

** Hooks

Enable evil-tex-mode for more text objects and support (explore this):

#+begin_src emacs-lisp
(add-hook 'LaTeX-mode-hook #'evil-tex-mode)
#+end_src

Turn on prettify symbols mode.
#+begin_src emacs-lisp
;; Turn on prettify-symbols for nicer LaTeX editting
(add-hook 'LaTeX-mode-hook 'prettify-symbols-mode)
#+end_src

Hook my custom functions (custom prettify symbols and LTR text):
#+begin_src emacs-lisp
(defun my-tex-hook ()
  (flip-hebrew)
  (prettify-latex-symbols))

(add-hook 'LaTeX-mode-hook 'my-tex-hook)

(add-hook 'plain-TeX-mode-hook 'my-tex-hook)

(add-hook 'AmS-TeX-mode-hook 'my-tex-hook)

(add-hook 'ConTeXt-mode-hook 'my-tex-hook)

(add-hook 'Texinfo-mode-hook 'my-tex-hook)

(add-hook 'docTeX-mode-hook 'my-tex-hook)

#+end_src





* Doom Keybindings
** Leader Key
#+BEGIN_SRC emacs-lisp
    ;; set leader key in normal state
    (evil-set-leader nil (kbd "SPC"))
#+END_SRC

** Basic Motions
#+BEGIN_SRC lisp
  ;; Leap.nvim like motion (avy-goto-char-2)

  (evil-define-key 'normal 'global (kbd "s") #'evil-avy-goto-char-2)

  ;; Basic movement keybindings
  (evil-define-key 'normal 'global (kbd "<leader>:") 'execute-extended-command)
  (evil-define-key 'normal 'global (kbd "<leader>.") 'counsel-find-file)
  (evil-define-key 'normal 'global (kbd "<leader>;") 'eval-expression)
#+END_SRC

A fix for the leader key not working in certain modes:
https://emacs.stackexchange.com/questions/70703/general-leader-key-not-working-in-some-modes-messages-on-initial-startup-onl

** File Keybindings (SPC-f)
#+BEGIN_SRC emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>fs") 'save-buffer)
(evil-define-key 'normal 'global (kbd "<leader>fr") 'counsel-recentf)
#+END_SRC

Perform search over =.emacs.d= directory:
#+BEGIN_SRC emacs-lisp
  (evil-define-key 'normal 'global (kbd "<leader>fp") (lambda()
							(interactive)
							(ivy-read
							"~/.emacs.d/"
							#'read-file-name-internal
							:matcher #'counsel--find-file-matcher)))
#+END_SRC
** Buffer Keybindings (SPC-b)
#+BEGIN_SRC emacs-lisp
;; Source: https://www.emacswiki.org/emacs/misc-cmds.el
(defun revert-buffer-no-confirm ()
    "Revert buffer without confirmation."
    (interactive)
    (revert-buffer :ignore-auto :noconfirm))

;; Source: https://emacs.stackexchange.com/questions/53196/how-to-quickly-revert-the-buffer
(defun reload-file-preserve-point ()
  (interactive)
  (when (or (not (buffer-modified-p))
            (y-or-n-p "Reverting will discard changes. Proceed?"))
    (save-excursion
      (revert-buffer t t t))
    (setq buffer-undo-list nil)
    (message "Buffer reverted")))

(evil-define-key 'normal 'global (kbd "<leader>bk") 'kill-this-buffer)
(evil-define-key 'normal 'global (kbd "<leader>bp") 'previous-buffer)
(evil-define-key 'normal 'global (kbd "<leader>bn") 'next-buffer)
(evil-define-key 'normal 'global (kbd "<leader>br") 'reload-file-preserve-point)
#+END_SRC

** Window Keybindings (SPC-w)
#+BEGIN_SRC emacs-lisp
(defun split-window-move-right()
  (interactive)
  (split-window-right)
  (windmove-right))

(evil-define-key 'normal 'global (kbd "<leader>wV") 'split-window-move-right)
(evil-define-key 'normal 'global (kbd "<leader>wc") 'delete-window)
(evil-define-key 'normal 'global (kbd "<leader>wl") 'windmove-right)
(evil-define-key 'normal 'global (kbd "<leader>wh") 'windmove-left)
(evil-define-key 'normal 'global (kbd "<leader>wk") 'windmove-up)
(evil-define-key 'normal 'global (kbd "<leader>wj") 'windmove-down)


;; Dired Keybindings
(evil-define-key 'normal 'global (kbd "<leader>dj") #'dired-jump)
(evil-define-key 'normal 'global (kbd "<leader>dp") #'peep-dired)
(evil-define-key 'normal 'global (kbd "<leader>dv") #'dired-view-file)
#+END_SRC

** Open Keybindings (SPC-o)
*** New Kitty window in PWD
#+BEGIN_SRC emacs-lisp
(defun macos/open-in-new-kitty-window ()
  (interactive)
  (shell-command "open -a kitty $PWD" nil nil))

(evil-define-key 'normal 'global (kbd "<leader>ok") #'macos/open-in-new-kitty-window)
#+END_SRC
** Magit Keybindings (SPC-g)
#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>gg") 'magit-status)
#+end_src
** Dired Keybindings
#+BEGIN_SRC emacs-lisp
(evil-define-key 'normal dired-mode-map
  (kbd "M-RET") 'dired-display-file
  (kbd "h") 'dired-up-directory
  (kbd "l") 'dired-find-file
  (kbd "m") 'dired-mark
  (kbd "t") 'dired-toggle-marks
  (kbd "u") 'dired-unmark
  (kbd "C") 'dired-do-copy
  (kbd "D") 'dired-do-delete
  (kbd "J") 'dired-goto-file
  (kbd "M") 'dired-do-chmod
  (kbd "O") 'dired-do-chown
  (kbd "P") 'dired-do-print
  (kbd "R") 'dired-do-rename
  (kbd "T") 'dired-do-touch
  ;;(kbd "Y") 'dired-copy-filenamecopy
  (kbd "Z") 'dired-do-compress
  (kbd "+") 'dired-create-directory
  (kbd "-") 'dired-up-directory

  ;; This makes the evil leader key work in dired
  (kbd "SPC") nil
  )
#+END_SRC



#+BEGIN_COMMENT
;;(custom-set-variables
 ;;;; custom-set-variables was added by Custom.
 ;;;; If you edit it by hand, you could mess it up, so be careful.
 ;;;; Your init file should contain only one such instance.
 ;;;; If there is more than one, they won't work right.
 ;;'(package-selected-packages '(avy use-package evil-collection counsel company)))
;;(custom-set-faces
 ;;;; custom-set-faces was added by Custom.
 ;;;; If you edit it by hand, you could mess it up, so be careful.
 ;;;; Your init file should contain only one such instance.
 ;;;; If there is more than one, they won't work right.
 ;;)
#+END_COMMENT




* Org Mode Packages
** org-auto-tangle
Use org-auto-tangle to automatically tangle files (a specific header needs to be added):

#+begin_src emacs-lisp
  (use-package org-auto-tangle
	  :ensure t
	  :defer t
	  :hook (org-mode)
	  :config
	  (setq org-auto-tangle-default t))
#+end_src
** toc-org-mode

#+begin_src emacs-lisp
  (use-package toc-org
    :ensure t
    :hook (org-mode))
  ;;(add-hook 'org-mode-hook 'toc-org-mode)
#+end_src

